server:
  port: 8081

service:
  tinkoff:
#    Ключ тинька. Нужно будет вынести в базу, если будет толк от этого
    token: "t.92Z55zO5fgs1P_dQn0-iYqdKPfg9sEZQ-Nz4CG3-ImSk6k1yA1UNFFiCuFZFVXJChPlwAV43FfnJ4F_WBWKrWA"
#    Кол-во дней, за которые нужно получить котировки
    days: 100
#    Шаг до паузы. Тинькоф Инвест позволяет сделать 100 запросов в минуту
    steps: 100
#    Ожидание в МС
    wait: 60000
    timeframe:
      - _DAY
      - _HOUR
      - _5_MINUTES
spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
